'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {Link2,LayoutDashboard,FilePlus2,ScanLine,ArrowLeftRight,KeyRound,ArrowUpRight,ShieldCheck,LockKeyhole,Plus,ChevronRight,FileText,FlaskConical,BookOpen} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {useWorkspace,type Workspace} from './useWorkspace';
import {Badge,PageTitle,Notice,date,short,bytes} from './common';
import {RegisterPage,VerifyPage} from './EvidenceFlows';
import {DetailsPage,TransfersPage} from './Custody';
import {AccountPage,DemoPage,AboutPage} from './Support';
import {registerAgentTools} from '@/lib/webmcp';
export type View='dashboard'|'register'|'verify'|'transfers'|'account'|'evidence'|'demo'|'about';
const navigation=[{href:'/',label:'Overview',icon:LayoutDashboard},{href:'/register',label:'Register evidence',icon:FilePlus2},{href:'/verify',label:'Verify evidence',icon:ScanLine},{href:'/transfers',label:'Custody transfers',icon:ArrowLeftRight}];
const sidebarLinkClass='nav-item flex w-full items-center overflow-hidden rounded-md text-left transition-colors focus-visible:outline-none';
function SidebarNavLink({href,label,icon:Icon,active,onClose}:{href:string;label:string;icon:typeof LayoutDashboard;active:boolean;onClose:()=>void}){return <Link href={href} className={sidebarLinkClass} data-active={active||undefined} aria-current={active?'page':undefined} onClick={onClose}><Icon/><span>{label}</span>{active&&<span className="nav-active-mark"/>}</Link>;}
function Navigation(){const path=usePathname();const {setOpenMobile}=useSidebar();return <SidebarMenu>{navigation.map(n=><SidebarMenuItem key={n.href}><SidebarNavLink {...n} active={path===n.href} onClose={()=>setOpenMobile(false)}/></SidebarMenuItem>)}</SidebarMenu>;}
function ResourcesNavigation({view}:{view:View}){const {setOpenMobile}=useSidebar();return <SidebarMenu>{[{href:'/demo',label:'Try the integrity demo',icon:FlaskConical},{href:'/about',label:'How verification works',icon:BookOpen}].map(n=><SidebarMenuItem key={n.href}><SidebarNavLink {...n} active={view===n.href.slice(1)} onClose={()=>setOpenMobile(false)}/></SidebarMenuItem>)}</SidebarMenu>;}
export function ProofChainApp({view,evidenceId}:{view:View;evidenceId?:string}){
 const w=useWorkspace();
 const [resolvedEvidenceId,setResolvedEvidenceId]=useState(evidenceId);
 const [queryReady,setQueryReady]=useState(Boolean(evidenceId)||!(view==='verify'||view==='evidence'));
 useEffect(()=>{
  registerAgentTools();
  if(!evidenceId && (view==='verify'||view==='evidence')){
   setResolvedEvidenceId(new URLSearchParams(window.location.search).get('id')||undefined);
  }
  setQueryReady(true);
 },[evidenceId,view]);
 return <SidebarProvider style={{'--sidebar-width':'244px'} as React.CSSProperties}><Sidebar className="app-sidebar"><SidebarHeader className="brand-header"><Link href="/" className="brand"><span className="brand-icon"><Link2/></span>ProofChain<span className="brand-period">.</span></Link><span className="brand-caption">EVIDENCE INTEGRITY WORKSPACE</span></SidebarHeader><SidebarContent className="sidebar-content"><p className="nav-label">WORKSPACE</p><Navigation/><div className="sidebar-secondary"><p className="nav-label">RESOURCES</p><ResourcesNavigation view={view}/></div></SidebarContent><SidebarFooter className="sidebar-footer"><div className="privacy-note"><LockKeyhole size={19}/><strong>Your files. Your device.</strong><p>Only proofs belong in the record.</p></div><Link className="account-link" href="/account"><span className="avatar">{w.user?.email?.slice(0,1).toUpperCase()||'L'}</span><div><strong>{w.user?.displayName || w.user?.email?.split('@')[0] || 'Local workspace'}</strong><small>{w.cloud?'Firebase account':'No account required'}</small></div><ChevronRight size={15}/></Link></SidebarFooter></Sidebar>
 <SidebarInset><header className="topbar"><div className="topbar-crumb"><SidebarTrigger/><span>Workspace</span><ChevronRight size={13}/><strong>{view==='evidence'?'Evidence record':view==='dashboard'?'Overview':view==='account'?'Account & device':view.charAt(0).toUpperCase()+view.slice(1)}</strong></div><div className="topbar-right"><span className="local-label"><LockKeyhole size={14}/> Local file processing</span><Link href="/account"><Badge tone={w.cloud?'green':'neutral'}>{w.cloud?'Firebase connected':'Local mode'}</Badge></Link></div></header>
 <div role="region" aria-label="Evidence workspace" className="workspace-main" id="main-content">{w.error&&<Notice error>{w.error}</Notice>}
 {view==='dashboard'&&<Dashboard w={w}/>}{view==='register'&&<RegisterPage w={w}/>}{view==='verify'&&queryReady&&<VerifyPage w={w} initialId={resolvedEvidenceId}/>}{view==='evidence'&&queryReady&&(resolvedEvidenceId?<DetailsPage w={w} id={resolvedEvidenceId}/>:<Notice error>No evidence ID was supplied.</Notice>)}{view==='transfers'&&<TransfersPage w={w}/>}{view==='account'&&<AccountPage w={w}/>}{view==='demo'&&<DemoPage/>}{view==='about'&&<AboutPage/>}
 </div><footer className="page-footer"><span><Link2 size={14}/> ProofChain · Verify evidence, not trust.</span><Link href="/about">What this proof establishes <ArrowUpRight size={13}/></Link></footer></SidebarInset></SidebarProvider>;
}
function Dashboard({w}:{w:Workspace}){
 const [search,setSearch]=useState('');const items=w.items.filter(e=>(e.title+e.id).toLowerCase().includes(search.toLowerCase()));
 return <><PageTitle eyebrow="YOUR EVIDENCE WORKSPACE" title="A clear record. Every step." description="Register, verify and track digital evidence with cryptographic proof." actions={<><Button variant="outline" asChild><Link href="/verify"><ScanLine/>Verify evidence</Link></Button><Button asChild><Link href="/register"><Plus/>Register evidence</Link></Button></>}/>
 <div className="overview-banner"><div className="banner-copy"><Badge><LockKeyhole size={13}/> LOCAL-FIRST BY DESIGN</Badge><h2>The proof travels.<br/>Your evidence stays with you.</h2><p>Hash files on your device. Sign every custody event.<br className="desktop-break"/> Give others a record they can independently verify.</p><Link href="/about">Understand the proof <ArrowUpRight size={16}/></Link></div><div className="proof-diagram" aria-label="File processed locally, fingerprint signed, proof shared"><div className="diagram-top"><span className="diagram-label">ON YOUR DEVICE</span><span className="diagram-label">IN THE RECORD</span></div><div className="diagram-flow"><div className="diagram-node"><FileText/><span>Evidence</span></div><div className="diagram-connector"><span>SHA-256</span></div><div className="diagram-node fingerprint"><span className="hash-symbol">#</span><span>Fingerprint</span></div><div className="diagram-connector"><span>SIGN</span></div><div className="diagram-node"><ShieldCheck/><span>Proof</span></div></div><div className="diagram-bottom"><LockKeyhole size={13}/><span>No file upload. No private key transfer.</span></div></div></div>
 <div className="stat-grid"><div className="stat-card"><div><span>Registered evidence</span><FileText size={18}/></div><strong>{w.loading?'—':w.items.length.toString().padStart(2,'0')}</strong><p>{w.cloud?'In your Firebase workspace':'Saved in this browser'}</p></div><div className="stat-card"><div><span>Signing identity</span><KeyRound size={18}/></div><strong className="stat-text">{w.key?'Ready to sign':w.error?'Unavailable':'Preparing…'}</strong><p>ECDSA P-256 · Device key</p></div><div className="stat-card"><div><span>Evidence uploaded</span><LockKeyhole size={18}/></div><strong>0 <em>bytes</em></strong><p>Files are processed locally</p></div></div>
 <div className="dashboard-bottom"><section className="panel evidence-panel"><div className="panel-heading"><div><h2>Evidence register</h2><p>Your files, identified by their fingerprints.</p></div><Badge>{w.items.length} records</Badge></div><div className="table-controls"><label className="sr-only" htmlFor="evidence-search">Search evidence</label><input id="evidence-search" placeholder="Search by title or evidence ID…" value={search} onChange={e=>setSearch(e.target.value)}/><span>{w.cloud?'Firebase':'This device'}</span></div>{w.loading?<div className="empty-state"><p>Loading evidence records…</p></div>:items.length?<div className="evidence-list">{items.map(e=><Link className="evidence-row" key={e.id} href={'/evidence?id='+encodeURIComponent(e.id)}><span className="file-tile"><FileText/></span><div className="evidence-row-main"><strong>{e.title}</strong><code>{short(e.id,10)}</code></div><div className="evidence-row-date"><span>{date(e.registeredAt)}</span><small>{bytes(e.fileSize)}</small></div><Badge>Registered</Badge><ChevronRight size={16}/></Link>)}</div>:<div className="empty-state"><span className="empty-icon"><FileText/></span><h3>{search?'No matching evidence':'Your first proof starts here'}</h3><p>{search?'Try a different title or evidence ID.':'Register a file to create its fingerprint and first signed custody record.'}</p>{!search&&<Button variant="outline" asChild><Link href="/register"><Plus/>Register your first file</Link></Button>}</div>}<div className="panel-footnote"><LockKeyhole size={13}/> Filenames, file contents and location metadata are not saved.</div></section>
 <aside className="demo-panel"><span className="demo-symbol"><FlaskConical/></span><p className="eyebrow">SEE THE DIFFERENCE</p><h2>One changed byte.<br/>A different verdict.</h2><p>Run a real cryptographic test with an original file and a modified copy.</p><div className="demo-mini"><span>Original file</span><span className="mini-check">Exact match</span><span>Changed file</span><span className="mini-fail">Match fails</span></div><Button asChild className="w-full"><Link href="/demo">Try the integrity demo <ArrowUpRight/></Link></Button><small>Real hashing. Real signatures. No signup.</small></aside></div>
 {!w.cloud&&<div className="local-callout"><span><KeyRound size={18}/><strong>Working locally?</strong> Your proofs stay in this browser. Export them to keep an independent copy.</span><Link href="/account">Connect your account <ArrowUpRight size={15}/></Link></div>}
 </>;
}
