'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeftRight,Check,Download,FileText,ScanLine,Send,ShieldCheck,X,ArrowRight,KeyRound} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Badge,CopyValue,FileDropzone,Notice,PageTitle,bytes,date,short} from './common';
import type {Workspace} from './useWorkspace';
import type {ProofBundle,ChainResult,FileAnalysis} from '@/types/proofchain';
import {getProof,appendEvent,downloadJson} from '@/lib/evidence/service';
import {canonical,parseBundle,verifyFullCustodyChain} from '@/lib/crypto/core';
import {appendLocalProof,localRead} from '@/lib/evidence/local-store';
import {friendlyError} from '@/lib/firebase/client';
export function Timeline({proof,chain}:{proof:ProofBundle;chain:ChainResult}){
 return <div className="timeline">{proof.custodyEvents.map((e,i)=>{const valid=chain.checks.filter(c=>c.eventId===e.eventId).every(c=>c.valid);return <div className="timeline-event" key={e.eventId}><span className={'timeline-marker '+(valid?'':'invalid')}>{e.eventType==='REGISTER'?<FileText/>:e.eventType==='TRANSFER'?<Send/>:e.eventType==='RECEIVE'?<ArrowLeftRight/>:<ScanLine/>}</span><details><summary><div><strong>{({REGISTER:'Evidence registered',TRANSFER:'Custody transfer initiated',RECEIVE:'Custody accepted',VERIFY:'File verification recorded',REJECT_TRANSFER:'Transfer rejected'})[e.eventType]}</strong><span>{date(e.timestamp)}</span></div><Badge tone={valid?'green':'red'}>{valid?<Check size={12}/>:<X size={12}/>} {valid?'Signature valid':'Check failed'}</Badge></summary><div className="event-detail"><label>Actor / device</label><CopyValue value={e.actorUserId}/><CopyValue value={e.actorKeyId}/>{e.toUserId&&<><label>Recipient</label><CopyValue value={e.toUserId}/></>}<label>Event hash · sequence {i}</label><CopyValue value={e.eventHash}/><label>Previous event</label><CopyValue value={e.previousEventHash}/><label>Signature</label><CopyValue value={e.signature}/></div></details></div>;})}</div>;
}
export function DetailsPage({w,id}:{w:Workspace;id:string}){
 const [proof,setProof]=useState<ProofBundle|null>(null),[chain,setChain]=useState<ChainResult|null>(null),[error,setError]=useState(''),[dialog,setDialog]=useState(false),[recipient,setRecipient]=useState(''),[busy,setBusy]=useState(false),[received,setReceived]=useState<FileAnalysis|null>(null);
 useEffect(()=>{if(w.loading||!w.uid)return;let active=true;(async()=>{try{const p=await getProof(id,w.cloud);const c=await verifyFullCustodyChain(p);if(active){setProof(p);setChain(c);}}catch(err){if(active)setError(friendlyError(err));}})();return()=>{active=false;};},[id,w.cloud,w.loading,w.uid]);
 async function action(type:'TRANSFER'|'RECEIVE'|'REJECT_TRANSFER'){
  if(!proof||!w.key)return;setBusy(true);setError('');
  try{const target=recipient.trim();if(type==='TRANSFER'&&(!/^[A-Za-z0-9_-]{1,160}$/.test(target)||target===w.uid))throw new Error('Enter the recipient’s account ID, different from your own.');
   if(type==='TRANSFER' && (proof.evidence.scope==='local')!==target.startsWith('LOCAL-'))throw new Error('Use a local recipient ID for a local record, or a Firebase account ID for a Firebase record.');
   const p=await appendEvent(proof,type,w.key,type==='TRANSFER'?target:null,type==='RECEIVE'?received?.sha256 ?? null:null);setProof(p);setChain(await verifyFullCustodyChain(p));setDialog(false);await w.refresh();
  }catch(err){setError(friendlyError(err));}finally{setBusy(false);}
 }
 if(!proof||!chain)return <><PageTitle eyebrow="EVIDENCE RECORD" title="Evidence details"/>{error?<Notice error>{error}</Notice>:<Notice>Loading the record and verifying every signature…</Notice>}</>;
 const e=proof.evidence;
 return <><PageTitle eyebrow="EVIDENCE RECORD" title={e.title} description={e.description || 'A cryptographically signed record of this evidence.'} actions={<><Button variant="outline" onClick={()=>downloadJson(proof)}><Download/>Export proof</Button><Button asChild><Link href={'/verify?id='+e.id}><ScanLine/>Verify file</Link></Button></>}/>{error&&<Notice error>{error}</Notice>}<div className="record-status"><Badge tone={chain.valid?'green':'red'}><ShieldCheck size={14}/>{chain.valid?'Supplied custody chain valid':'Custody chain invalid'}</Badge><Badge>{e.scope==='local'?'Local record':'Firebase record'}</Badge><span>Registered {date(e.registeredAt)}</span></div><div className="flow-layout"><div><section className="panel form-panel"><div className="panel-heading inline"><h2>Evidence fingerprint</h2><FileText size={18}/></div><label>Evidence ID</label><CopyValue value={e.id}/><label>SHA-256</label><CopyValue value={e.sha256}/><div className="split-data"><div><label>File type</label><p>{e.mimeType}</p></div><div><label>File size</label><p>{bytes(e.fileSize)}</p></div></div><Notice>No evidence file is stored in this record. Use “Verify file” to test a local copy.</Notice></section><section className="panel timeline-panel"><div className="panel-heading"><div><h2>Chain of custody</h2><p>Every event linked. Every signature checked.</p></div><Badge>{proof.custodyEvents.length} events</Badge></div><Timeline proof={proof} chain={chain}/></section></div><aside className="flow-aside"><section className="panel side-explainer"><ArrowLeftRight/><h3>Current custody</h3><label>Custodian account ID</label><CopyValue value={chain.currentCustodian}/>{chain.pendingRecipient?<><Badge tone="amber">Awaiting recipient verification</Badge><label>Pending recipient</label><CopyValue value={chain.pendingRecipient}/></>:<p>No pending transfer.</p>}{chain.valid&&chain.currentCustodian===w.uid&&!chain.pendingRecipient&&<Button className="w-full" onClick={()=>setDialog(true)}><Send/>Transfer custody</Button>}</section><section className="panel side-explainer"><KeyRound/><h3>Provenance & time</h3><label>Recorded C2PA summary</label><p>{e.c2paStatus}</p><p className="fine-print">Re-inspect your local file to validate credentials. A stored summary is not a portable C2PA proof.</p><label>Trusted timestamp</label><Badge tone="amber">Not anchored</Badge><p className="fine-print">Event times are device-reported. No independent timestamp authority is used.</p></section><p className="fine-print">Keep an exported proof and key fingerprint independently. Valid signatures alone do not establish legal identity or that this is the latest history.</p></aside></div>
 {chain.valid&&chain.pendingRecipient===w.uid&&<section className="panel receipt-panel"><PageTitle eyebrow="PENDING CUSTODY" title="Verify the file you received" description="The sender shares the actual file outside ProofChain. Select your received copy here."/><FileDropzone onAnalysis={setReceived} label="Select your received evidence file"/>{received&&<Notice error={received.sha256!==e.sha256}>{received.sha256===e.sha256?'EXACT FILE VERIFIED — you can now accept custody.':'EXACT MATCH FAILED — custody acceptance is blocked.'}</Notice>}<div className="form-actions"><Button variant="outline" disabled={busy} onClick={()=>void action('REJECT_TRANSFER')}>Reject transfer</Button><Button disabled={busy||received?.sha256!==e.sha256} onClick={()=>void action('RECEIVE')}><Check/>Accept custody</Button></div></section>}
 <Dialog open={dialog} onOpenChange={setDialog}><DialogContent><DialogHeader><DialogTitle>Transfer custody</DialogTitle><DialogDescription>Initiate a signed transfer. Custody changes only after the recipient verifies their file and accepts.</DialogDescription></DialogHeader><label htmlFor="recipient">Recipient account ID</label><Input id="recipient" placeholder={e.scope==='local'?'LOCAL-…':'Firebase account UID'} value={recipient} onChange={e=>setRecipient(e.target.value)}/><p className="field-help">Ask the recipient to copy their account ID from Account & device. No email or file is sent by this action.</p>{error&&<Notice error>{error}</Notice>}{e.scope==='local'&&<Notice>After signing, export the updated proof and give it to the recipient along with the file through your chosen channel. They can import it on Custody transfers.</Notice>}<DialogFooter><Button variant="outline" onClick={()=>setDialog(false)}>Cancel</Button><Button disabled={busy||!recipient.trim()} onClick={()=>void action('TRANSFER')}>{busy?'Signing…':'Sign transfer'}<ArrowRight/></Button></DialogFooter></DialogContent></Dialog></>;
}
export function TransfersPage({w}:{w:Workspace}){
 const [records,setRecords]=useState<{proof:ProofBundle;chain:ChainResult}[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{if(w.loading)return;let active=true;(async()=>{try{const all=await Promise.all(w.items.map(async e=>{const proof=await getProof(e.id,w.cloud);return {proof,chain:await verifyFullCustodyChain(proof)};}));if(active)setRecords(all);}catch(err){if(active)setError(friendlyError(err));}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[w.items,w.cloud,w.loading]);
 const pending=records.filter(r=>r.chain.pendingRecipient);
 return <><PageTitle eyebrow="03 / TWO-SIDED HANDOVER" title="Custody transfers" description="A transfer is complete only when the recipient verifies and accepts the file."/>{error&&<Notice error>{error}</Notice>}<div className="panel form-panel"><h2>Receive a transfer</h2><p className="muted">Share your account ID with the sender. Receive the evidence file through your chosen secure channel.</p><CopyValue value={w.uid||'Preparing account…'}/>{!w.cloud&&<><label htmlFor="transfer-bundle">Import the sender’s updated proof bundle</label><input className="file-input" id="transfer-bundle" type="file" accept=".json" onChange={async ev=>{const file=ev.target.files?.[0];if(!file)return;setError('');try{if(file.size>8*1024*1024)throw new Error('Proof bundle exceeds 8 MB.');const proof=parseBundle(JSON.parse(await file.text())),chain=await verifyFullCustodyChain(proof);if(!chain.valid)throw new Error('The supplied custody chain is invalid.');if(proof.evidence.scope!=='local'||chain.pendingRecipient!==w.uid)throw new Error('This local transfer is not addressed to your account ID.');const existing=await localRead<ProofBundle>('proofs',proof.evidence.id);if(existing){if(proof.custodyEvents.length<existing.custodyEvents.length||canonical(proof.custodyEvents.slice(0,existing.custodyEvents.length))!==canonical(existing.custodyEvents))throw new Error('The imported proof conflicts with the history stored on this device.');await appendLocalProof(proof,existing.checkpoint.headHash);}else await appendLocalProof(proof);await w.refresh();}catch(err){setError(friendlyError(err));}ev.target.value='';}}/><p className="field-help">Imported signatures and custody links are checked before the record is saved.</p></>}</div><section className="panel transfer-list"><div className="panel-heading"><h2>Awaiting acceptance</h2><Badge>{pending.length} transfers</Badge></div>{loading?<div className="empty-state">Checking custody records…</div>:!pending.length?<div className="empty-state"><span className="empty-icon"><ArrowLeftRight/></span><h3>No pending transfers</h3><p>Incoming and outgoing custody requests will appear here.</p></div>:pending.map(({proof,chain})=><Link className="evidence-row" href={'/evidence?id='+encodeURIComponent(proof.evidence.id)} key={proof.evidence.id}><span className="file-tile"><ArrowLeftRight/></span><div className="evidence-row-main"><strong>{proof.evidence.title}</strong><code>{short(proof.evidence.id)}</code></div><Badge tone={chain.valid?'amber':'red'}>{!chain.valid?'Invalid record':chain.pendingRecipient===w.uid?'Your acceptance needed':'Awaiting recipient'}</Badge><ArrowRight size={18}/></Link>)}</section></>;
}
