'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowRight,Check,ShieldCheck,LockKeyhole,FileJson,Download,Plus,XCircle,Link2,KeyRound,ScanLine} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import type {Workspace} from './useWorkspace';
import {Badge,CopyValue,FileDropzone,Notice,PageTitle,bytes} from './common';
import type {ChainResult,FileAnalysis,ProofBundle} from '@/types/proofchain';
import {registerEvidence,getProof,downloadJson,appendEvent} from '@/lib/evidence/service';
import {parseBundle,verifyFullCustodyChain} from '@/lib/crypto/core';
import {hammingDistance} from '@/lib/evidence/analysis';
import {friendlyError} from '@/lib/firebase/client';
export function RegisterPage({w}:{w:Workspace}){
 const [analysis,setAnalysis]=useState<FileAnalysis|null>(null),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[fingerprint,setFingerprint]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter();
 return <><PageTitle eyebrow="01 / CREATE A RECORD" title="Register evidence" description="Create a signed fingerprint. Keep the original file in your own custody."/><div className="flow-layout"><section className="panel form-panel"><div className="section-label"><span>01 &nbsp; SELECT & ANALYSE</span><Badge>Local processing</Badge></div><FileDropzone onAnalysis={setAnalysis}/><form onSubmit={async e=>{e.preventDefault();if(!analysis||!w.key)return;setBusy(true);setError('');try{const proof=await registerEvidence(analysis,title,description,w.key,w.cloud,fingerprint);router.push('/evidence?id='+encodeURIComponent(proof.evidence.id));}catch(err){setError(friendlyError(err));}finally{setBusy(false);}}}><div className="section-label form-divider">02 &nbsp; DESCRIBE THE EVIDENCE</div><label htmlFor="evidence-title">Evidence title <span className="required">*</span></label><Input id="evidence-title" required maxLength={160} placeholder="e.g. Parking lot photograph" value={title} onChange={e=>setTitle(e.target.value)}/><p className="field-help">Choose a title you are comfortable recording. The original filename is never saved.</p><label htmlFor="description">Description <span className="muted">(optional)</span></label><Textarea id="description" maxLength={2000} rows={3} placeholder="Add context for the evidence record…" value={description} onChange={e=>setDescription(e.target.value)}/>{analysis?.perceptualHash&&<label className="checkbox-label"><Checkbox checked={fingerprint} onCheckedChange={v=>setFingerprint(v===true)}/>Include a visual fingerprint for optional image similarity checks.</label>}{error&&<Notice error>{error}</Notice>}<div className="form-actions"><span><LockKeyhole size={14}/> {w.cloud?'Save proof to Firebase':'Save proof in this browser'}</span><Button type="submit" disabled={!analysis||!title.trim()||!w.key||busy}>{busy?'Signing & saving…':'Register evidence'}<ArrowRight/></Button></div></form></section><aside className="flow-aside"><div className="panel side-explainer"><ShieldCheck/><h3>What gets registered?</h3><p>A fingerprint of every byte, your chosen title and a signed registration event.</p><ul><li><Check/>SHA-256 fingerprint</li><li><Check/>File size and type</li><li><Check/>Public verification key</li><li><Check/>Signed custody event</li></ul><div className="aside-divider"/><strong>What stays on your device?</strong><p>The evidence file, original filename, extracted metadata and private signing key.</p></div><Notice>{w.cloud?'This proof will be available to participants through your Firebase account.':'You are in local mode. Export the proof after registration. Sign in for shared Firebase custody records.'}</Notice><p className="fine-print">Registration records integrity, not whether the file depicts a real event. The registration time is device-reported, not a trusted timestamp.</p></aside></div></>;
}
export function VerifyPage({w,initialId=''}:{w:Workspace;initialId?:string}){
 const [method,setMethod]=useState('id'),[id,setId]=useState(initialId),[bundle,setBundle]=useState<ProofBundle|null>(null),[analysis,setAnalysis]=useState<FileAnalysis|null>(null),[result,setResult]=useState<{proof:ProofBundle;chain:ChainResult;exact:boolean}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[threshold,setThreshold]=useState(8),[recorded,setRecorded]=useState(false);
 const version=useRef(0);const invalidate=()=>{version.current++;setResult(null);setError('');setRecorded(false);};
 async function verify(){const current=version.current;setBusy(true);setError('');try{const proof=method==='bundle'?bundle:await getProof(id.trim(),w.cloud);if(!proof)throw new Error('Select a proof bundle first.');if(!analysis)throw new Error('Select your evidence file.');const chain=await verifyFullCustodyChain(proof);if(current===version.current)setResult({proof,chain,exact:analysis.sha256===proof.evidence.sha256});}catch(err){if(current===version.current)setError(friendlyError(err));}finally{setBusy(false);}}
 const distance=result&&analysis?.perceptualHash&&result.proof.evidence.perceptualHash?hammingDistance(analysis.perceptualHash,result.proof.evidence.perceptualHash):null;
 return <><PageTitle eyebrow="02 / INDEPENDENT VERIFICATION" title="Verify evidence" description="Compare a local file against a recorded proof. Every byte counts."/><div className="flow-layout"><section className="panel form-panel"><Tabs value={method} onValueChange={v=>{setMethod(v);invalidate();}}><TabsList className="method-tabs"><TabsTrigger value="id"><ScanLine/>Evidence ID</TabsTrigger><TabsTrigger value="bundle"><FileJson/>Proof bundle</TabsTrigger></TabsList><TabsContent value="id"><label htmlFor="lookup-id">Evidence ID</label><Input id="lookup-id" placeholder="EV-…" value={id} onChange={e=>{setId(e.target.value);invalidate();}}/><p className="field-help">{w.cloud?'Look up an evidence record available to your Firebase account.':'Look up a record saved on this device. For external evidence, use a proof bundle.'}</p></TabsContent><TabsContent value="bundle"><label htmlFor="bundle-file">Exported proof bundle</label><input id="bundle-file" className="file-input" type="file" accept=".json,.proofchain.json" onChange={async e=>{invalidate();setBundle(null);const f=e.target.files?.[0];if(!f)return;const current=version.current;try{if(f.size>8*1024*1024)throw new Error('Proof bundles must be smaller than 8 MB.');const p=parseBundle(JSON.parse(await f.text()));if(current===version.current)setBundle(p);}catch(err){setError(friendlyError(err));}}}/><p className="field-help">The bundle is read locally. It is not uploaded.</p>{bundle&&<Badge>{bundle.evidence.title} · {bundle.custodyEvents.length} events</Badge>}</TabsContent></Tabs><div className="form-divider"/><FileDropzone onAnalysis={a=>{setAnalysis(a);invalidate();}} label="Select the file to verify"/>{error&&<Notice error>{error}</Notice>}<div className="form-actions"><span><LockKeyhole size={14}/> Verified on this device</span><Button disabled={!analysis||busy||(method==='id'?!id.trim():!bundle)} onClick={()=>void verify()}>{busy?'Verifying signatures…':'Verify evidence'}<ArrowRight/></Button></div></section><aside className="flow-aside"><div className="panel side-explainer"><ScanLine/><h3>Three separate checks.</h3><div className="numbered-note"><span>1</span><div><strong>Exact file integrity</strong><p>Does SHA-256 match the registered file?</p></div></div><div className="numbered-note"><span>2</span><div><strong>Custody chain</strong><p>Do the events link together in the correct order?</p></div></div><div className="numbered-note"><span>3</span><div><strong>Digital signatures</strong><p>Did the supplied signing keys sign these events?</p></div></div></div><Notice>Renaming a file preserves its fingerprint. Changing even one byte produces a different fingerprint.</Notice></aside></div>
 {result&&analysis&&<section className="panel verification-results" aria-live="polite"><div className={'verdict '+(result.exact?'pass':'fail')}>{result.exact?<ShieldCheck/>:<XCircle/>}<div><p>EXACT FILE INTEGRITY</p><h2>{result.exact?'VERIFIED EXACT':'EXACT MATCH FAILED'}</h2><span>{result.exact?'The file matches the digest in this proof bundle.':'The local file has a different SHA-256 digest.'}</span></div><Badge tone={result.exact?'green':'red'}>{bytes(analysis.size)}</Badge></div><div className="result-body"><div className="split-data"><div><label>Registered SHA-256</label><CopyValue value={result.proof.evidence.sha256}/></div><div><label>Local SHA-256</label><CopyValue value={analysis.sha256}/></div></div><div className="result-checks"><div><Link2/><span>Hash chain</span><Badge tone={result.chain.hashChainValid?'green':'red'}>{result.chain.hashChainValid?'VALID':'INVALID'}</Badge></div><div><KeyRound/><span>Signatures</span><Badge tone={result.chain.signaturesValid?'green':'red'}>{result.chain.signaturesValid?'VALID':'INVALID'}</Badge></div><div><ShieldCheck/><span>Custody rules</span><Badge tone={result.chain.valid?'green':'red'}>{result.chain.valid?'VALID':'INVALID'}</Badge></div></div><h3 className={result.exact&&result.chain.valid?'success-text':'error-text'}>{result.exact&&result.chain.valid?'VERIFIED INTACT — supplied proof':result.chain.valid?'NOT VERIFIED — file mismatch':'CUSTODY CHAIN INVALID'}</h3>{!result.chain.valid&&result.chain.checks.filter(c=>!c.valid).map((c,i)=><Notice error key={i}>{c.check}: {c.reason}</Notice>)}{!result.exact&&distance!==null&&<div className="similarity"><Badge tone="amber">{distance<=threshold?'POSSIBLE DERIVATIVE':'No close visual match'}</Badge><p>Image dHash distance: <strong>{distance} / 64</strong>. This does not establish provenance or exact integrity.</p><label>Similarity threshold <input aria-label="Similarity threshold" type="number" min="0" max="64" value={threshold} onChange={e=>setThreshold(Math.max(0,Math.min(64,Number(e.target.value))))}/></label></div>}<Notice>Signatures establish control of the supplied keys, not legal identity. Keep a trusted copy of the key fingerprint and checkpoint; this bundle alone cannot prove the history is the latest.</Notice><div className="form-actions"><Button variant="outline" onClick={()=>downloadJson(result.proof)}><Download/>Export proof</Button>{result.exact&&result.chain.valid&&w.key&&[result.chain.currentCustodian,result.chain.pendingRecipient].includes(w.uid)&&<Button disabled={busy||recorded} onClick={async()=>{setBusy(true);try{const next=await appendEvent(result.proof,'VERIFY',w.key!,null,analysis.sha256);setResult({...result,proof:next,chain:await verifyFullCustodyChain(next)});setRecorded(true);}catch(err){setError(friendlyError(err));}finally{setBusy(false);}}}>{recorded?<Check/>:<Plus/>}{recorded?'Verification recorded':'Sign verification event'}</Button>}</div></div></section>}
 </>;
}
